version: '3'
services:
  drupal:
    image: bitnami/drupal:latest
    ports:
      - 8080:80
    volumes:
      - drupal_data:/bitnami/drupal
    environment:
      - MARIADB_HOST=mariadb
      - MARIADB_PORT_NUMBER=3306
      - DRUPAL_DATABASE_USER=YAM428
      - DRUPAL_DATABASE_PASSWORD=30718008
      - DRUPAL_DATABASE_NAME=final
      - ALLOW_EMPTY_PASSWORD=yes

  mariadb:
    image: bitnami/mariadb:latest
    volumes:
      - mariadb_data:/bitnami/mariadb
    environment:
      - MARIADB_USER=YAM428
      - MARIADB_PASSWORD=30718008
      - MARIADB_DATABASE=final
      - ALLOW_EMPTY_PASSWORD=yes

  nginx:
    image: nginx:latest
    volumes:
      - nginx_data:/etc/nginx
      - certbot_data:/etc/letsencrypt
    ports:
      - 80:80
      - 443:443
    environment:
      - DOMAIN=mustafatufekci.me

  certbot:
    image: certbot/certbot:latest
    volumes:
      - certbot_data:/etc/letsencrypt
    environment:
      - DOMAIN=mustafatufekci.me


volumes:
  drupal_data:
    driver: local
  mariadb_data:
    driver: local
  nginx_data:
    driver: local
  certbot_data:
    driver: local
